// <copyright file="GlobalSuppressions.cs" company="Johannes Ebner">
// Copyright (c) Johannes Ebner. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root or https://spdx.org/licenses/MIT.html for full license information.
// </copyright>

// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "Razor Page", Scope = "type", Target = "~T:Claimini.Web.Pages.IndexModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "Razor Page", Scope = "type", Target = "~T:Claimini.Web.Pages.ErrorModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "Razor Page", Scope = "type", Target = "~T:Claimini.Web.Pages.ContactModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "Razor Page", Scope = "type", Target = "~T:Claimini.Web.Pages.AboutModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "Razor Page", Scope = "type", Target = "~T:Claimini.Web.Pages.Customers.IndexModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "Razor Page", Scope = "type", Target = "~T:Claimini.Web.Pages.Customers.EditModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "Razor Page", Scope = "type", Target = "~T:Claimini.Web.Pages.Customers.DetailsModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "Razor Page", Scope = "type", Target = "~T:Claimini.Web.Pages.Customers.DeleteModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "Razor Page", Scope = "type", Target = "~T:Claimini.Web.Pages.Customers.CreateModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "Razor Page", Scope = "type", Target = "~T:Claimini.Web.Pages.Account.Manage.ChangePasswordModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "Razor Page", Scope = "type", Target = "~T:Claimini.Web.Pages.Account.Manage.Disable2faModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "Razor Page", Scope = "type", Target = "~T:Claimini.Web.Pages.Account.Manage.EnableAuthenticatorModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "Razor Page", Scope = "type", Target = "~T:Claimini.Web.Pages.Account.Manage.ExternalLoginsModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "Razor Page", Scope = "type", Target = "~T:Claimini.Web.Pages.Account.Manage.GenerateRecoveryCodesModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "Razor Page", Scope = "type", Target = "~T:Claimini.Web.Pages.Account.Manage.ResetAuthenticatorModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "Razor Page", Scope = "type", Target = "~T:Claimini.Web.Pages.Account.Manage.SetPasswordModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "Razor Page", Scope = "type", Target = "~T:Claimini.Web.Pages.Account.Manage.TwoFactorAuthenticationModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "Razor Page", Scope = "type", Target = "~T:Claimini.Web.Pages.Account.ConfirmEmailModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "Razor Page", Scope = "type", Target = "~T:Claimini.Web.Pages.Account.ExternalLoginModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "Razor Page", Scope = "type", Target = "~T:Claimini.Web.Pages.Account.LockoutModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "Razor Page", Scope = "type", Target = "~T:Claimini.Web.Pages.Account.*")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "Razor Page", Scope = "type", Target = "~T:Claimini.Web.Pages.*")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "Razor Page", Scope = "type", Target = "~T:Claimini.Web.Pages.Account.AccessDeniedModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "Razor Page", Scope = "type", Target = "~T:Claimini.Web.Pages.Account.Articles.*")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "Razor Page", Scope = "type", Target = "~T:Claimini.Web.Pages.Articles.CreateModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "Razor Page", Scope = "type", Target = "~T:Claimini.Web.Pages.Articles.DeleteModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "Razor Page", Scope = "type", Target = "~T:Claimini.Web.Pages.Articles.DetailsModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "Razor Page", Scope = "type", Target = "~T:Claimini.Web.Pages.Articles.EditModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "Razor Page", Scope = "type", Target = "~T:Claimini.Web.Pages.Articles.IndexModel")]
